### ISSUE TITLE
Expose Compile in JsEngineBase for better support of V8

### ISSUE THREAD

**Issue by huan086** [Taritsyn/JavaScriptEngineSwitcher#10]
V8 supports compilation and reusing the compiled scripts. Supporting a Compile step (returns an object), and having Evaluate (that takes an object) on the compile script would allow consumers to improve performance.

For engines that do not support compilation, Compile could return an object that encapsulates the string to be evaluated. Evaluate would then evaluate the encapsulated string as usual.

**Comment by Taritsyn** [comment]
In the JavaScriptEngineSwitcher there will be no specific methods.

If you need this functionality, then use the Microsoft ClearScript.V8 directly.

**Comment by Taritsyn** [comment]
Hello, Jeow!

This feature was implemented in [version 3.0.0](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.0.0) and supported by the following modules: [ChakraCore](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/ChakraCore), [Jint](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Jint), [Jurassic](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Jurassic), [MSIE](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/MSIE) and [V8](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/V8). You can read about how this feature works in the [“How to upgrade applications to version 3.X > Script pre-compilation”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/How-to-upgrade-applications-to-version-3.X#script-pre-compilation) subsection of documentation.
