### ISSUE TITLE
Resources should conform to correct ICU standard for naming

### ISSUE THREAD

**Issue by timheuer** [Taritsyn/JavaScriptEngineSwitcher#102]
I just hit an issue on a package that depended on this one with a collision in case-sensitivity on resource folders/copying.  `ru-ru` is not technically the standard for ICU/ISO naming standard but instead should be `ru-RU`

Ref: https://unicode-org.github.io/icu/userguide/locale/#country-code
Relevant snippet 
```
To allow for these differences among specific geographical, political, or cultural regions, 
locales are specified by two-letter, uppercase codes.
```

**Comment by Taritsyn** [comment]
Hello, Tim!

Thanks for information! This problem is solved in [version 3.19.0](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.19.0).

**Comment by stefanloerwald** [comment]
Hi @Taritsyn,

This change seems to break builds in some environments, see logs here: https://github.com/excubo-ag/WebCompiler/runs/8056232048?check_suite_focus=true

> /home/runner/.dotnet/sdk/6.0.400/Microsoft.Common.CurrentVersion.targets(4809,5): warning MSB3026: Could not copy "/home/runner/.nuget/packages/javascriptengineswitcher.v8/3.19.0/lib/net5.0/ru-RU/JavaScriptEngineSwitcher.V8.resources.dll" to "bin/Release/net6.0/ru-RU/JavaScriptEngineSwitcher.V8.resources.dll". Beginning retry 1 in 1000ms. Could not find a part of the path '/home/runner/work/WebCompiler/WebCompiler/WebCompiler/bin/Release/net6.0/ru-RU/JavaScriptEngineSwitcher.V8.resources.dll'.  [/home/runner/work/WebCompiler/WebCompiler/WebCompiler/WebCompiler.csproj] 

Could you please have a look?
Thanks
Stefan

**Comment by Taritsyn** [comment]
Hello, @StefanLoerwald!

It seems that the AutoprefixerHost package creates a `ru-ru` directory, which other packages with the correct name of this directory (`ru-RU`) cannot overwrite on Unix-based operating systems.

As a solution to this problem, I suggest updating the AutoprefixerHost package to version 3.0.22.

**Comment by stefanloerwald** [comment]
Thanks @Taritsyn, that fixes things.
