### ISSUE TITLE
Request to support Deno 

### ISSUE THREAD

**Issue by zakuru** [Taritsyn/JavaScriptEngineSwitcher#107]
Hello,

Would is be possible to support DENO as JS environment ?

**Comment by zakuru** [comment]
I could do it actually if i can have some guidance

**Comment by Taritsyn** [comment]
Hello, Zakuru!

Deno is a JS runtime, not an engine. JavaScript Engine Switcher library is focused specifically on engines.

At one time, at the request of some users, I made a [JavaScriptEngineSwitcher.Node](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Node) module. It is quite out of the main concept of my library and few people use it. In general, I see no reason to create and maintain a second such module within my library.

If you have a desire and ability to make a .NET wrapper for Deno, then make your own project similar to the [Jering.Javascript.NodeJS](https://github.com/JeringTech/Javascript.NodeJS).

**Comment by zakuru** [comment]
Ok got will try to do it myself 👌
But juste à questions when you say more focused on engine and les s on runtime its by choice and not tech reasons/ limitation right ?

**Comment by DaniilSokolyuk** [comment]
Or you can add Deno support in [Jering.Javascript.NodeJS](https://github.com/JeringTech/Javascript.NodeJS)

**Comment by zakuru** [comment]
yes @DaniilSokolyuk I was about to start from there 
But then there will still be some work to do in JavaScriptEngineSwitcher

**Comment by Taritsyn** [comment]
> But just a questions when you say more focused on engine and less on runtime its by choice and not tech reasons/ limitation right?

JavaScript Engine Switcher library was created for engines, not for runtimes.

> But then there will still be some work to do in JavaScriptEngineSwitcher

For what? What is this work?

**Comment by Taritsyn** [comment]
Capabilities of the JavaScript Engine Switcher's modules are limited by the ECMAScript specification. If your goal is to run a Node.js modules without any modifications, then the JavaScript Engine Switcher library will not suit you.

**Comment by zakuru** [comment]
Ok will look into it thanks
