### ISSUE TITLE
Any way to debug js or capture console output?

### ISSUE THREAD

**Issue by hzexe** [Taritsyn/JavaScriptEngineSwitcher#108]
In some case js run in node and browser,but not work correct with js engine.
So wish some way to detect what happened.

Any idea?

**Comment by Taritsyn** [comment]
Hello!

What module of the JavaScript Engine Switcher are you using?

**Comment by Taritsyn** [comment]
Looking ahead, I will only say that the JavaScript Engine Switcher library is focused on working with pure ECMAScript and does not support APIs specific for browsers and Node.js (including the `console` object). Specific debugging mechanisms are provided for some modules (see the [documentation](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki)).

In addition, to implement your own console, you can use the methods that responsible for .NET-iterop (`EmbedHostObject` or `EmbedHostType`):

```csharp
var log = new Action<string>(Console.WriteLine);

using (IJsEngine engine = new JintJsEngine())
{
    engine.EmbedHostObject("log", log);
    engine.Execute("log('Current time: ' + new Date());");
}
```

In this example, the JavaScriptEngineSwitcher.Jint module is used, but it can also work with all modules except the JavaScriptEngineSwitcher.Node and JavaScriptEngineSwitcher.Vroom.

**Comment by hzexe** [comment]
Thanks,change to v8 engine and enable remote debuging follow [documentation](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki).
then found the problem in  return value of the function atob
