### ISSUE TITLE
deprecated?

### ISSUE THREAD

**Issue by StefH** [Taritsyn/JavaScriptEngineSwitcher#111]
You indicated that this JavaScriptEngineSwitcher.V8.*** is deprecated?

Can you show the replacement when using Microsoft.Clearscript for this code:
``` c #
JsEngineSwitcher.Current.DefaultEngineName = V8JsEngine.EngineName;
JsEngineSwitcher.Current.EngineFactories.AddV8();
```

**Comment by StefH** [comment]
When I just remove the NuGets and replace these by the Microsoft.ClearScript, I get build error:

![image](https://github.com/Taritsyn/JavaScriptEngineSwitcher/assets/249938/f000b7e2-bc77-4bcb-b912-6328d5788504)

**Comment by Taritsyn** [comment]
You must have at least 3 packages installed:
 * JavaScriptEngineSwitcher.Core
 * JavaScriptEngineSwitcher.V8
 * Microsoft.ClearScript.V8.Native.win-x64

**Comment by StefH** [comment]
Thank you.
