### ISSUE TITLE
JavaScriptEngineSwitcher.Core.JsEngineNotFoundException

### ISSUE THREAD

**Issue by yeshwanth-t** [Taritsyn/JavaScriptEngineSwitcher#113]
Hi,

I have been using v3.1.0 for quite long time and this was working well. Now, I upgraded to v3.21.0 and getting the below error.
**_JavaScriptEngineSwitcher.Core.JsEngineNotFoundException: Could not find a factory, that creates an instance of the JavaScript engine with name `ChakraCoreJsEngine`._**

The below is the versions list that I got installed.

- JavaScriptEngineSwitcher.Core 3.21.0
- JavaScriptEngineSwitcher.ChakraCore 3.21.0
- JavaScriptEngineSwitcher.ChakraCore.Native.win-x64 3.21.0
- JavaScriptEngineSwitcher.ChakraCore.Native.win-x86 3.21.0
- AdvancedStringBuilder 0.1.0
- System.Buffers 4.5.1

I tried to rollback to older version but still the error occurs. Is there anything that got changed?
More detailed explanation in below link.
https://sitecore.stackexchange.com/questions/36568/bundletransformer-assettranslationexception-could-not-find-factory

**Comment by Taritsyn** [comment]
Hello!

Try to re-read the [“Registration of JS engines”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Registration-of-JS-engines) section of documentation.

**Comment by yeshwanth-t** [comment]
Thanks @Taritsyn . All those registrations are already in place in my web application. Is there any breaking changes from 3.1.0 to 3.21.0?

**Comment by Taritsyn** [comment]
> Is there any breaking changes from 3.1.0 to 3.21.0?

No.

It's possible that you need to [read this](https://github.com/Taritsyn/BundleTransformer/wiki/Sass-and-SCSS#how-to-upgrade-applications-to-version-113x).

**Comment by Taritsyn** [comment]
> JavaScriptEngineSwitcher.Core.JsEngineNotFoundException: Could not find a factory, that creates an instance of the JavaScript engine with name `ChakraCoreJsEngine`.

This error message means that JS engine has not been registered. Check your the `Global.asax.cs` file there should be the following line of code:

```csharp
JsEngineSwitcherConfig.Configure(JsEngineSwitcher.Current);
```

**Comment by yeshwanth-t** [comment]
> ```cs
> JsEngineSwitcher
> ```

I do have the below code in my Global.asax.cs

public override void Application_Start(object sender, EventArgs e)    
{
            IdentityModelEventSource.ShowPII = true;
            JsEngineSwitcherConfig.Configure((JsEngineSwitcher)JsEngineSwitcher.Current);
        }

**Comment by Taritsyn** [comment]
> JsEngineSwitcherConfig.Configure((JsEngineSwitcher)JsEngineSwitcher.Current);

Why are you doing a type conversion? It seems that you have incorrectly migrated from version 2.X to 3.X (see the [“How to upgrade applications to version 3.X”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/How-to-upgrade-applications-to-version-3.X) section of documentation).

**Comment by B-Ahdoot** [comment]
I am working with @yeshwanth-t. We have 2 workstations already running using the typecasting above. Without the typecast, we receive this error: 
cannot convert from 'JavaScriptEngineSwitcher.Core.IJsEngineSwitcher' to 'JavaScriptEngineSwitcher.Core.JsEngineSwitcher'

**Comment by Taritsyn** [comment]
@B-Ahdoot, As far as I understand, you control contents of the `App_Start/JsEngineSwitcherConfig.cs` file yourself. Just change argument type of the `Configure` method to the `IJsEngineSwitcher` and you won't need type conversion.

To avoid the error described by @yeshwanth-t, you need to ensure that the `JsEngineSwitcherConfig.Configure` method is called before calling the `BundleConfig.RegisterBundles` method. As an example, you can look at the [BundleTransformer.Sample.AspNet45.Mvc4](https://github.com/Taritsyn/BundleTransformer/tree/7789e08cc06127c7679516025e7231c01967eff0/samples/BundleTransformer.Sample.AspNet45.Mvc4) demo project (pay special attention to the [`App_Start/JsEngineSwitcherConfig.cs`](https://github.com/Taritsyn/BundleTransformer/blob/7789e08cc06127c7679516025e7231c01967eff0/samples/BundleTransformer.Sample.AspNet45.Mvc4/App_Start/JsEngineSwitcherConfig.cs) and [`Global.asax.cs`](https://github.com/Taritsyn/BundleTransformer/blob/7789e08cc06127c7679516025e7231c01967eff0/samples/BundleTransformer.Sample.AspNet45.Mvc4/Global.asax.cs) files).

**Comment by yeshwanth-t** [comment]
@Taritsyn Thank you. The above two sugessions worked great and I am able to resolve those errors. Once again thank you for actively supporting us!!
