### ISSUE TITLE
Warning NETSDK1187

### ISSUE THREAD

**Issue by yodasad** [Taritsyn/JavaScriptEngineSwitcher#117]
Hello!

This warning is generated during package restore:

> Warning NETSDK1187 Package JavaScriptEngineSwitcher.V8 3.17.1 has a resource with the locale 'ru-ru'. This locale has been normalized to the standard format 'ru-RU' to prevent casing issues in the build. Consider notifying the package author about this casing issue.

**Comment by Taritsyn** [comment]
Hello!

This error has been fixed in [version 3.19.0](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.19.0).
