### ISSUE TITLE
The futex facility returned an unexpected error code when running ChakraCoreJsEngine on Linux

### ISSUE THREAD

**Issue by haihai1999** [Taritsyn/JavaScriptEngineSwitcher#118]
1: Related information:
      ChakraCoreJsEngine ver 3.24.1
     Application. net 8
     Server Ubuntu 22.4
2: Problems that arise
     The code is as follows:
        Var chakraCoreSet=new ChakraCoreSets
        {
            DisableEval=false,
            Enabling ExperimentalFeatures=true,
            DisableBackgroundWork=false
        };
       Using (var_engine=new ChakraCoreJsEngine (chakraCoreSet))
       {
           _engine Execute (jsCode)// JsCode is the executed JS code, with around 50 lines of code
       }
When executing code, Linux directly reports the error The futex facility returned an unexpected error code service has been stopped.
When the configuration item DisableBackgroundWork in chakraCoreSet is changed to true, the above error will not occur.

**Comment by Taritsyn** [comment]
Hello!

> ChakraCoreJsEngine ver 3.24.1

First, try updating to [version 3.26.0](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.26.0). A similar error ([“Futex_fatal_error in ./nptl/pthread_mutex_lock.c”](https://github.com/chakra-core/ChakraCore/issues/6931)) was recently fixed in the [original library](https://github.com/chakra-core/ChakraCore).

**Comment by Christian-Oleson** [comment]
I recently hit this on version: JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64 Version="3.21.0"
I'll try the upgrade to see if that resolves my problem.

**Comment by Christian-Oleson** [comment]
Updating my Versions to latest in both Native.Linux and the main JavaScriptEngineSwitcher fix the issue for me.
