### ISSUE TITLE
Add support for microsoft/node-api-dotnet

### ISSUE THREAD

**Issue by cb-eli** [Taritsyn/JavaScriptEngineSwitcher#119]
Node API for .NET: JavaScript + .NET Interop

https://github.com/microsoft/node-api-dotnet

It can be a nice addition

**Comment by Taritsyn** [comment]
Hello!

Node.js is a JS runtime, not an engine. JavaScript Engine Switcher library is focused specifically on engines.

At one time, at the request of some users, I made a [JavaScriptEngineSwitcher.Node](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Node) module. It is quite out of the main concept of my library and few people use it. In general, I see no reason to create and maintain a second such module within my library.

You will get much more benefits if you use the Microsoft.JavaScript.NodeApi directly.

**Comment by cb-eli** [comment]
> Hello!
> 
> Node.js is a JS runtime, not an engine. JavaScript Engine Switcher library is focused specifically on engines.
> 
> At one time, at the request of some users, I made a [JavaScriptEngineSwitcher.Node](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Node) module. It is quite out of the main concept of my library and few people use it. In general, I see no reason to create and maintain a second such module within my library.
> 
> You will get much more benefits if you use the Microsoft.JavaScript.NodeApi directly.

Thanks for the response 🙏
