### ISSUE TITLE
V8 config can be null

### ISSUE THREAD

**Issue by Daniel15** [Taritsyn/JavaScriptEngineSwitcher#12]
`GetV8Configuration` returns the value of `ConfigurationManager.GetSection("jsEngineSwitcher/v8")`. If this configuration section is not in the `Web.config` or `App.config`, this returns `null`, resulting in a NullReferenceException in V8JsEngine's constructor:

![image](https://cloud.githubusercontent.com/assets/91933/7103876/52d6398e-e070-11e4-83c2-664eb9913918.png)

**Comment by Taritsyn** [comment]
During installation of `JavaScriptEngineSwitcher.V8` package the `jsEngineSwitcher/v8` configuration section is automatically added to configuration file (`Web.config` or `App.config`).

**Comment by Daniel15** [comment]
True, but it should still handle the case of the config being null (eg. If
I manually install it rather than using the NuGet package).

**Comment by Taritsyn** [comment]
If config being null, then will not work a `JsEngineSwitcher.Current.CreateDefaultJsEngineInstance` method.

**Comment by Daniel15** [comment]
True - However you can still create a V8 engine through `new V8JsEngine()`, which will crash with a NullReferenceException. The constructor should handle if `v8Config` is null.

**Comment by Taritsyn** [comment]
OK. In next release I will fix this error.

**Comment by Taritsyn** [comment]
In the [JavaScriptEngineSwitcher.V8 version 1.2.6](http://nuget.org/packages/JavaScriptEngineSwitcher.V8/1.2.6) was fixed this error.
