### ISSUE TITLE
Add support for JavaScript.net

### ISSUE THREAD

**Issue by Daniel15** [Taritsyn/JavaScriptEngineSwitcher#17]
See:

https://rushfrisby.com/which-net-javascript-engine-is-the-fastest/
https://github.com/JavascriptNet/Javascript.Net
https://github.com/reactjs/React.NET/issues/293

**Comment by Taritsyn** [comment]
Hello, Daniel!

This is yet another wrapper around V8. Not updated for more than a year, and, most likely, will not support of .NET Core.

Moreover, [“Which .NET JavaScript Engine is the fastest?”](https://rushfrisby.com/which-net-javascript-engine-is-the-fastest/) review is already old - 2 August, 2014.

In addition, I have a negative experience of using the Noesis.Javascript.

Therefore, I see no reason to create module for it.

**Comment by Daniel15** [comment]
Thanks, makes sense. I'll close this issue.
