### ISSUE TITLE
ClearScriptV8-64.dll and v8-x64.dll in ASP.NET Core project

### ISSUE THREAD

**Issue by Daniel15** [Taritsyn/JavaScriptEngineSwitcher#18]
Hey Andrey, do you have any suggestions on how to handle the ClearScript DLLs in an ASP.NET Core project? The issue is that these DLL files are not automatically copied over to the `bin` directory on compile.

**Comment by Daniel15** [comment]
It looks like I can use `xcopy` in a postcompile step, it's really ugly though, due to the paths being hardcoded:
```
    "postcompile": [
      "xcopy /Y C:\\Users\\Daniel\\.nuget\\packages\\JavaScriptEngineSwitcher.V8\\1.5.2\\content\\ClearScript.V8 %project:Directory%\\bin\\Debug\\net452\\win7-x64\\ClearScript.V8\\*"
    ],
```

**Comment by Taritsyn** [comment]
Hello, Daniel!

I solved this problem in [version 2.0](https://github.com/Taritsyn/JavaScriptEngineSwitcher/tree/2.0). Today I will try to release the first alpha.

**Comment by Daniel15** [comment]
Thank you for working on it! :smile:

**Comment by Taritsyn** [comment]
JavaScript Engine Switcher [version 2.0.0 Alpha 1](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v2.0.0-alpha.1) released.

**Comment by Taritsyn** [comment]
JavaScript Engine Switcher [version 2.0.0](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v2.0.0) released.

**Comment by Daniel15** [comment]
Thank you @Taritsyn!
