### ISSUE TITLE
Consider making the supported data types configurable

### ISSUE THREAD

**Issue by dalenewman** [Taritsyn/JavaScriptEngineSwitcher#19]
I know, that [Jint](https://github.com/sebastienros/jint) (for sure) can handle more data types than `bool`, `int`, `double`, and `string`.  Have you considered making the supported data types configurable?

Thanks, and thanks for your contribution to open source :-)

PS: I am using this in my project [Transformalize](https://github.com/dalenewman/Transformalize).

**Comment by Taritsyn** [comment]
Hello, Dale!

Quote from project description:

> JavaScript Engine Switcher determines **unified interface for access to the basic features** of popular JavaScript engines (MSIE JavaScript Engine for .Net, Microsoft ClearScript.V8, Jurassic, Jint and ChakraCore). This library allows you to quickly and easily switch to using of another JavaScript engine.

If I make the supported data types configurable, then you can not easily switch to another JS engine.

**Comment by dalenewman** [comment]
Okay it's your call.  Thanks for your consideration.
