### ISSUE TITLE
Add support for VroomJs

### ISSUE THREAD

**Issue by Daniel15** [Taritsyn/JavaScriptEngineSwitcher#20]
VroomJs is another wrapper around V8. The main advantage of VroomJs is that it works on Linux and Mac OS. It's useful for people that want to use V8 on those platforms. @pauldotknopf has a fork of VroomJs that runs on .NET Core.

NuGet package: https://www.nuget.org/packages/VroomJs/
GitHub repo: https://github.com/pauldotknopf/vroomjs-core

In ReactJS.NET (currently using JavaScriptEngineSwitcher 1.x) I have a custom IJsEngine for an older version of VroomJs, but it would be good to get support into JavaScriptEngineSwitcher. https://github.com/reactjs/React.NET/blob/release-2.5.0/src/React.Core/VroomJsEngine.cs

**Comment by Taritsyn** [comment]
Hello, Daniel!

When I have some free time, I'll take care of this task.

**Comment by Taritsyn** [comment]
Hello, Daniel!

Module based on the VroomJs added in the [JavaScript Engine Switcher version 2.0.1](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v2.0.1). 

Currently, VroomJs has the following issues, that do not allow it to fully comply with requirements of the JavaScript Engine Switcher:

1. Not supported `undefined` type.
2. Errors when calling methods of embedded objects and types, that have several overloaded versions.
3. Errors when accessing to the fields of embedded objects.
4. Inability to embed the instances of delegates.
5. There's no method, that starts the garbage collection.
