### ISSUE TITLE
JsEngineSwitcher is not mockable in a unit test

### ISSUE THREAD

**Issue by Daniel15** [Taritsyn/JavaScriptEngineSwitcher#21]
I wanted to write a unit test that tests some code that uses `JsEngineSwitcher`, but it's not possible to mock this class as it's `sealed` and there's no interface. Could you please make it extend an `IJsEngineSwitcher` interface so that code that uses it can be unit tested?

**Comment by Daniel15** [comment]
Actually I guess there's no benefit in mocking it, I can just use an instance of the real `JsEngineSwitcher` and register some mock engines in the `EngineFactories`.

**Comment by Taritsyn** [comment]
> I wanted to write a unit test that tests some code that uses `JsEngineSwitcher`, but it's not possible to mock this class as it's `sealed` and there's no interface. Could you please make it extend an `IJsEngineSwitcher` interface so that code that uses it can be unit tested?

@Daniel15 This feature was implemented in [version 3.0.0 Alpha 2](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.0.0-alpha.2).
