### ISSUE TITLE
Make Exception serializable

### ISSUE THREAD

**Issue by huan086** [Taritsyn/JavaScriptEngineSwitcher#22]
I'm running JavaScript in my Entity Framework seed method. When an exception occurs, it throws
`Type 'JavaScriptEngineSwitcher.Core.JsEngineLoadException' in assembly 'JavaScriptEngineSwitcher.Core, Version=2.0.3.0, Culture=neutral, PublicKeyToken=c608b2a8cc9e4472' is not marked as serializable.`

So make exceptions serializable. See
https://blogs.msdn.microsoft.com/agileer/2013/05/17/the-correct-way-to-code-a-custom-exception-class/

**Comment by Taritsyn** [comment]
Hello, Huan!

I will fix this problem in the next release.

You have found the cause of the `JsEngineLoadException`? What JS engine are you using?

**Comment by huan086** [comment]
JsEngineLoadException was due to the new nuget package not having the native DLLs bundled by default. Installed the 2 native packages and the error went away.

**Comment by Taritsyn** [comment]
OK

**Comment by Daniel15** [comment]
Note that .NET Core doesn't have binary serialization, so you need to use conditional comments like this:
```
#if NET40 || NET45
	[Serializable]
#endif
``` 
eg. see https://github.com/reactjs/React.NET/blob/89bc9cbecef5e549f746d645d42706aa3a6d3219/src/React.Core/Exceptions/BabelException.cs#L18

**Comment by Taritsyn** [comment]
Hello, Huan!

In [JavaScript Engine Switcher 2.1.2](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v2.1.2) fixed this error.
