### ISSUE TITLE
GetResourceAsString does not work as expected

### ISSUE THREAD

**Issue by avonwyss** [Taritsyn/JavaScriptEngineSwitcher#23]
In the .NET framework, from day one on, there has been an overload for [`Assembly.GetManifestResourceStream()`](https://msdn.microsoft.com/en-us/library/5kx66y1a(v=vs.110).aspx) which takes a type and a string (name) as arguments.

So when I started to use `JavaScriptEngineSwitcher` and saw that there are two overloads of the `GetResourceAsString`, I of course expected them to mirror the behavior of `Assembly.GetManifestResourceStream`, that is, when a type is specified it should take the namespace into account. But unfortunately it doesn't...

Of course I can prepend the namespace to the name, but that's not a good solution because it makes the code more susceptible to breaking (change the default namespace in the project properties and bam! its broken at runtime).

**Comment by Taritsyn** [comment]
Hello, Arsene!

In [JavaScript Engine Switcher 2.2.0](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v2.2.0) solved this problem.
