### ISSUE TITLE
NuGet package is built in debug mode

### ISSUE THREAD

**Issue by gunnim** [Taritsyn/JavaScriptEngineSwitcher#38]
Is there a reason for this? Seems like it would be better to distribute the package in release mode.

(I checked with a directory scanning fork of https://assemblyinformation.codeplex.com/)

**Comment by Taritsyn** [comment]
Hello, Gunnar!

All assemblies for the packages I'm building in release mode. In which package did you find this problem?

**Comment by gunnim** [comment]
ru-ru\JavaScriptEngineSwitcher.Core.resources.dll
for netstandard 1.3 and net45

**Comment by gunnim** [comment]
Should've been more specific initially.
I just gave the results a cursory look and didn't notice it wasn't the main assemblies :)

**Comment by Taritsyn** [comment]
Look a source code of [script to build the JavaScriptEngineSwitcher.Core package](https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/master/NuGet/JavaScriptEngineSwitcher.Core/build-package.cmd). You can see, that everywhere are used directories with the release assemblies.

**Comment by gunnim** [comment]
Interesting.... 

But as you can see here it still seems to have been uploaded to nuget without optimizations.
Same applies to your latest 3.0.0-alpha1 build
But.. since it's just a resource assembly i guess it isn't a big deal but noteworthy nonetheless :)

![image](https://user-images.githubusercontent.com/17432315/28502389-d5a94908-6fe0-11e7-977e-f4e8892c9007.png)

**Comment by Daniel15** [comment]
@gunnim - This is just a resource assembly and **only** contains a resource file with strings in it. It does not contain any code, so there's no difference between a debug and a release build. The framework might always compile them in debug mode because of that.

**Comment by gunnim** [comment]
@Daniel15 Makes sense, I definately jumped the gun with this issue. 
I had just completed a scan and found dozens of other packages that had their core assemblies released in debug mode, so i was kindof in autopilot mode notifying maintainers :).

**Comment by Taritsyn** [comment]
@gunnim @Daniel15 It seems that this is a bug in `dotnet.exe`. Moreover, if build a library by using Visual Studio 2017, then there is no such error.
