### ISSUE TITLE
NodeJS as a JS Engine? 

### ISSUE THREAD

**Issue by asmagin** [Taritsyn/JavaScriptEngineSwitcher#39]
Hi @Taritsyn,
do you think it makes sense to implement standalone NodeJs server as an option of a JS engine?

**Comment by Taritsyn** [comment]
Hello, Alex!

Bad idea. Why waste the resources for I/O, when there are already modules supporting V8 engine: [JavaScriptEngineSwitcher.V8](https://www.nuget.org/packages/JavaScriptEngineSwitcher.V8) and [JavaScriptEngineSwitcher.Vroom](https://www.nuget.org/packages/JavaScriptEngineSwitcher.Vroom)?

**Comment by asmagin** [comment]
I understand that you will pay some toll on I/O. However, you will be able to scale those engines independently and outside Windows server.

**Comment by Taritsyn** [comment]
Nobody prevents you from making your own unofficial module, that implements this functionality. I don't plan to develop such a module.

If you just need Linux and OS X support, then try the [JavaScriptEngineSwitcher.ChakraCore](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-ChakraCore) module.

**Comment by asmagin** [comment]
Let's leave implementation efforts questions aside.

I'm using your module as a part of Sitecore CMS and Linux is not an option for its core, even dotNet Core is not there yet. On the other side application is have by itself, licensing doesn't make it easier as well.

I just would like to get you perspective it on such approach as it was actually a path that Microsoft took in [there JavaScriptServices](https://github.com/aspnet/JavaScriptServices).

As you've been working on JS switcher for quite a while, you know it inside out. So you think that you will have only performance problems from such approach?

**Comment by Taritsyn** [comment]
If you need this functionality, then implement your own unofficial module. You just need to inherit the <code title="JavaScriptEngineSwitcher.Core.JsEngineBase">JsEngineBase</code> abstract class, implement the <code title="JavaScriptEngineSwitcher.Core.IJsEngineFactory">IJsEngineFactory</code> interface and make your own version of the `JsEngineFactoryCollectionExtensions` class. If you will publish your unofficial module, then add a `.Unofficial` suffix to the name of package.

I also recommend to you see the [Edge.js](https://github.com/tjanczuk/edge) project.

**Comment by Taritsyn** [comment]
Hello, Alex!

If you have problems with performance of the ReactJS.NET, then I recommend to watch [this video](https://www.facebook.com/afishamansarda/videos/1730212723669439/) in Russian language (ReactJS.NET's presentation starts from 83rd minute).

**Comment by asmagin** [comment]
Thanks, will check it out.
