### ISSUE TITLE
The 3.x version depends on Clearscript.V8 5.5.0.0, but can't find it

### ISSUE THREAD

**Issue by svdoever** [Taritsyn/JavaScriptEngineSwitcher#42]
From release notes:
Microsoft ClearScript.V8 was updated to version 5.5.0 (support of V8 version 6.2.414.40);

But can only find version 4.9.0.0 as nuget package. Any idea how to resolve this dependency?

**Comment by Taritsyn** [comment]
Hello, Serge!

> But can only find version 4.9.0.0 as nuget package. Any idea how to resolve this dependency?

Read the “V8” section of [“Misconceptions about the JavaScript Engine Switcher version 2.X”](https://github.com/reactjs/React.NET/issues/409) article.

Also I recommend you to see the [related section of  documentation](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-V8).

**Comment by svdoever** [comment]
@Taritsyn thanks, misconceptions article was an eyeopener:-)
