### ISSUE TITLE
ChakraCore does not support c # "object" and "dynamic"

### ISSUE THREAD

**Issue by Aditrc** [Taritsyn/JavaScriptEngineSwitcher#43]
> JavaScriptEngineSwitcher.Core.JsRuntimeException:“ReferenceError: Could not find suitable method or not enough arguments to invoke of 'Amethod ' method of the host object.
   at Global code (Script Document:1:1)”

```
void Amethod (object p)
{
    Console.WriteLine(p);
}
```
```
engine.Execute("xxx.Amethod (123)");
```

in other engines will not throw this

**Comment by Taritsyn** [comment]
Hello!

This error was fixed in version [3.0.0 Alpha 8](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.0.0-alpha.8). Until the end of year I will try to transfer this patch together with other updates to version 2.X.
