### ISSUE TITLE
Trying to get Chakracore engine running in a microsoft/dotnet:2 docker container

### ISSUE THREAD

**Issue by stuart-beattie** [Taritsyn/JavaScriptEngineSwitcher#44]
Has anyone had any success running the chakracore engine in a Linux docker container (hosted in ECS on AWS) based on the microsoft/dotnet:2-sdk image?

I have installed this package:

JavaScriptEngineSwitcher.ChakraCore.Native.debian-x64 v3.0.0.0-alpha9

However I still get the following error:

"Unable to load DLL 'ChakraCore': The specified module or one of its dependencies could not be found."

Everything working fine running in windows locally.

Is there something i'm missing or something else I need to do? Thanks.

**Comment by Taritsyn** [comment]
This package is deprecated. Instead, it is recommended to use a [LibSassHost.Native.linux-x64](https://www.nuget.org/packages/LibSassHost.Native.linux-x64/) package.

**Comment by Taritsyn** [comment]
This package is deprecated. Instead, it is recommended to use a [JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64](https://www.nuget.org/packages/JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64/3.0.0-alpha9) package.

**Comment by stuart-beattie** [comment]
Ah ok great thanks I'll give that a go.

**Comment by stuart-beattie** [comment]
Thankyou, that does the trick! Much appreciated.
