### ISSUE TITLE
Worker process crash with JavascriptEngineSwitcher.Msie + BundleTransformer.Less on Windows Server 2012 Standard

### ISSUE THREAD

**Issue by jeremyZX** [Taritsyn/JavaScriptEngineSwitcher#52]
Starting with the April 2018 security rollup patch, there is a hard crash of the IIS worker process when using JavascriptEngineSwitcher.Msie and BundleTransformer.Less.  This crash is observed on Windows Server 2012 Standard.  It is unknown at the moment whether the crash occurs on later versions of Windows Server.

It's unknown whether this issue originates in JavascriptEngineSwitcher.Msie (unlikely), or in MsieJavascriptEngine (more likely).  It's also unknown whether this issue is .less specific, or if it may be observed with other file types as well.  I'm adding it here because a simple repro case does not require a direct dependency to MsieJavascriptEngine.

We've been able to work around this issue both by uninstalling the patch ([kb4093123](https://support.microsoft.com/en-us/help/4093123/windows-server-2012-update-kb4093123)), as well as switching from MSIE to another engine (e.g. ChakraCore.)

A simple repro project is attached.

[BundleTransformerMsieTest-src.zip](https://github.com/Taritsyn/JavaScriptEngineSwitcher/files/1943777/BundleTransformerMsieTest-src.zip)

Requests to any .less file via the LessAssetHandler cause the IIS worker process to crash with the following events written to the Windows Event log:

> Log Name:      Application
> Source:        .NET Runtime
> Date:          4/24/2018 12:26:36 PM
> Event ID:      1026
> Task Category: None
> Level:         Error
> Keywords:      Classic
> User:          N/A
> Description:
> Application: w3wp.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.AccessViolationException
> Stack:
>    at MsieJavaScriptEngine.ActiveScript.IActiveScriptParse64.ParseScriptText(System.String, System.String, System.Object, System.String, UIntPtr, UInt32, MsieJavaScriptEngine.ActiveScript.ScriptTextFlags, System.Object ByRef, System.Runtime.InteropServices.ComTypes.EXCEPINFO ByRef)
>    at MsieJavaScriptEngine.ActiveScript.IActiveScriptParse64.ParseScriptText(System.String, System.String, System.Object, System.String, UIntPtr, UInt32, MsieJavaScriptEngine.ActiveScript.ScriptTextFlags, System.Object ByRef, System.Runtime.InteropServices.ComTypes.EXCEPINFO ByRef)
>    at MsieJavaScriptEngine.ActiveScript.ActiveScriptWrapper64.ParseScriptText(System.String, System.String, System.Object, System.String, UIntPtr, UInt32, MsieJavaScriptEngine.ActiveScript.ScriptTextFlags)
>    at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.InnerExecute(System.String, System.String, Boolean)
>    at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase+&lt;&gt;c__DisplayClass34_0.&lt;Evaluate&gt;b__0()
>    at MsieJavaScriptEngine.ScriptDispatcher+&lt;&gt;c__DisplayClass12_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].&lt;Invoke&gt;b__0()
>    at MsieJavaScriptEngine.ScriptDispatcher.StartThread()
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Threading.ThreadHelper.ThreadStart()
> 
> Event Xml:
> &lt;Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"&gt;
>   &lt;System&gt;
>     &lt;Provider Name=".NET Runtime" /&gt;
>     &lt;EventID Qualifiers="0"&gt;1026&lt;/EventID&gt;
>     &lt;Level&gt;2&lt;/Level&gt;
>     &lt;Task&gt;0&lt;/Task&gt;
>     &lt;Keywords&gt;0x80000000000000&lt;/Keywords&gt;
>     &lt;TimeCreated SystemTime="2018-04-24T16:26:36.000000000Z" /&gt;
>     &lt;EventRecordID&gt;19019&lt;/EventRecordID&gt;
>     &lt;Channel&gt;Application&lt;/Channel&gt;
>     &lt;Security /&gt;
>   &lt;/System&gt;
>   &lt;EventData&gt;
>     &lt;Data&gt;Application: w3wp.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.AccessViolationException
> Stack:
>    at MsieJavaScriptEngine.ActiveScript.IActiveScriptParse64.ParseScriptText(System.String, System.String, System.Object, System.String, UIntPtr, UInt32, MsieJavaScriptEngine.ActiveScript.ScriptTextFlags, System.Object ByRef, System.Runtime.InteropServices.ComTypes.EXCEPINFO ByRef)
>    at MsieJavaScriptEngine.ActiveScript.IActiveScriptParse64.ParseScriptText(System.String, System.String, System.Object, System.String, UIntPtr, UInt32, MsieJavaScriptEngine.ActiveScript.ScriptTextFlags, System.Object ByRef, System.Runtime.InteropServices.ComTypes.EXCEPINFO ByRef)
>    at MsieJavaScriptEngine.ActiveScript.ActiveScriptWrapper64.ParseScriptText(System.String, System.String, System.Object, System.String, UIntPtr, UInt32, MsieJavaScriptEngine.ActiveScript.ScriptTextFlags)
>    at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase.InnerExecute(System.String, System.String, Boolean)
>    at MsieJavaScriptEngine.ActiveScript.ActiveScriptJsEngineBase+&lt;&gt;c__DisplayClass34_0.&lt;Evaluate&gt;b__0()
>    at MsieJavaScriptEngine.ScriptDispatcher+&lt;&gt;c__DisplayClass12_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].&lt;Invoke&gt;b__0()
>    at MsieJavaScriptEngine.ScriptDispatcher.StartThread()
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Threading.ThreadHelper.ThreadStart()
> &lt;/Data&gt;
>   &lt;/EventData&gt;
> &lt;/Event&gt;

> Log Name:      Application
> Source:        Application Error
> Date:          4/24/2018 12:26:36 PM
> Event ID:      1000
> Task Category: (100)
> Level:         Error
> Keywords:      Classic
> User:          N/A
> Description:
> Faulting application name: w3wp.exe, version: 8.0.9200.16384, time stamp: 0x50108835
> Faulting module name: jscript9.dll, version: 10.0.9200.22411, time stamp: 0x5ab67156
> Exception code: 0xc0000005
> Fault offset: 0x000000000009de9b
> Faulting process id: 0x18b4
> Faulting application start time: 0x01d3dbe902db98e6
> Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
> Faulting module path: C:\Windows\SYSTEM32\jscript9.dll
> Report Id: 41d7c693-47dc-11e8-941b-001422091778
> Faulting package full name: 
> Faulting package-relative application ID: 
> Event Xml:
> &lt;Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"&gt;
>   &lt;System&gt;
>     &lt;Provider Name="Application Error" /&gt;
>     &lt;EventID Qualifiers="0"&gt;1000&lt;/EventID&gt;
>     &lt;Level&gt;2&lt;/Level&gt;
>     &lt;Task&gt;100&lt;/Task&gt;
>     &lt;Keywords&gt;0x80000000000000&lt;/Keywords&gt;
>     &lt;TimeCreated SystemTime="2018-04-24T16:26:36.000000000Z" /&gt;
>     &lt;EventRecordID&gt;19020&lt;/EventRecordID&gt;
>     &lt;Channel&gt;Application&lt;/Channel&gt;
>     &lt;Security /&gt;
>   &lt;/System&gt;
>   &lt;EventData&gt;
>     &lt;Data&gt;w3wp.exe&lt;/Data&gt;
>     &lt;Data&gt;8.0.9200.16384&lt;/Data&gt;
>     &lt;Data&gt;50108835&lt;/Data&gt;
>     &lt;Data&gt;jscript9.dll&lt;/Data&gt;
>     &lt;Data&gt;10.0.9200.22411&lt;/Data&gt;
>     &lt;Data&gt;5ab67156&lt;/Data&gt;
>     &lt;Data&gt;c0000005&lt;/Data&gt;
>     &lt;Data&gt;000000000009de9b&lt;/Data&gt;
>     &lt;Data&gt;18b4&lt;/Data&gt;
>     &lt;Data&gt;01d3dbe902db98e6&lt;/Data&gt;
>     &lt;Data&gt;c:\windows\system32\inetsrv\w3wp.exe&lt;/Data&gt;
>     &lt;Data&gt;C:\Windows\SYSTEM32\jscript9.dll&lt;/Data&gt;
>     &lt;Data&gt;41d7c693-47dc-11e8-941b-001422091778&lt;/Data&gt;
>     &lt;Data&gt;
>     &lt;/Data&gt;
>     &lt;Data&gt;
>     &lt;/Data&gt;
>   &lt;/EventData&gt;
> &lt;/Event&gt;

**Comment by Taritsyn** [comment]
Hello, Jeremy!

What version of Internet Explorer is installed on the server?

**Comment by jeremyZX** [comment]
IE 10, which (I believe) is the latest available for Windows Server 2012 Standard

**Comment by Taritsyn** [comment]
Hello, Jeremy!

> We've been able to work around this issue both by uninstalling the patch (kb4093123), ...

If problem was solved by uninstalling the patch, then most likely this error is in the `jscript9.dll` assembly. Such error can not be fixed in .NET wrapper ([MSIE JavaScript Engine for .NET](https://github.com/Taritsyn/MsieJavaScriptEngine)). Unfortunately, Microsoft has recently made similar errors: [“Control stack size for ChakraCore engine”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/49) and [“Process is terminating due to StackOverflowException”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/48).

At the moment, [JavaScriptEngineSwitcher.ChakraCore](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-ChakraCore) is more preferable for use on the server, than the [JavaScriptEngineSwitcher.Msie](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-MSIE). The main advantage of the JavaScriptEngineSwitcher.Msie is ability to debug scripts by using Visual Studio.
