### ISSUE TITLE
Allow reinitialization of JSEngineSwitcher

### ISSUE THREAD

**Issue by Dadstart** [Taritsyn/JavaScriptEngineSwitcher#53]
In response to a configuration change on my service I sometimes need to switch engines. Currently there's no way to reinitialize the JSEngineSwitcher so my only solution is to unload my app domain and let IIS create a new app domain (where my code uses the new default engine).

JSEngineSwitcher needs a way to be reinitialized. Just changing JsEngineSwitcher.Instance.DefaultEngineName doesn't actually change the engine being used.

**Comment by Taritsyn** [comment]
Hello, Andrew!

Try to using a [`CreateEngine`](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Creating-instances-of-JS-engines#createengine-method) method with a variable instead of a constant.
