### ISSUE TITLE
System.Runtime.InteropServices.RuntimeInformation not required for .NET Framework 4.7.1

### ISSUE THREAD

**Issue by flcdrg** [Taritsyn/JavaScriptEngineSwitcher#54]
I believe this NuGet package wouldn't be required when targetting 4.7.1 as it it built in

https://docs.microsoft.com/en-au/dotnet/api/system.runtime.interopservices.runtimeinformation?view=netframework-4.7.1

**Comment by Taritsyn** [comment]
Hello, David!

Does dependency on the `System.Runtime.InteropServices.RuntimeInformation` package lead to any conflicts or errors in your project?

**Comment by Taritsyn** [comment]
OK. Thanks for information!

**Comment by Taritsyn** [comment]
Hello, David!

This fix was included in [version 3.0.0 Beta 4](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.0.0-beta.4).

**Comment by flcdrg** [comment]
Awesome!
