### ISSUE TITLE
Nil - can't locate function name

### ISSUE THREAD

**Issue by deandob** [Taritsyn/JavaScriptEngineSwitcher#57]
Hi,

I'm trying to use JavaScriptEngineSwitcher for the NiL JS engine as it is the best fit for my use-case, however it seems there is an issue with being able to call functions, with the switcher reporting JavaScriptEngineSwitcher.Core.JsRuntimeException: 'The function with the name 'negate' does not exist.'
yet when I run exactly the same code with Jint it works fine. Is the NiL wrapper not ready for use? The code is from your test cases, as below:

`           JsEngineSwitcher engineSwitcher = (JsEngineSwitcher)JsEngineSwitcher.Current;
            engineSwitcher.EngineFactories
                .AddNiL(new NiLSettings
                {
                    StrictMode = true
                })
                //.AddJint()
                //.AddJurassic()
                //.AddMsie(new MsieSettings
                //{
                //    UseEcmaScript5Polyfill = true,
                //    UseJson2Library = true
                //})
                //.AddV8()
                ;

            engineSwitcher.DefaultEngineName = NiLJsEngine.EngineName;
            //engineSwitcher.DefaultEngineName = JintJsEngine.EngineName;

            const string functionCode = @"function negate(value) {
	            return -1 * value;
            }";
            using (var engine = JsEngineSwitcher.Current.CreateDefaultEngine())
            {
                try
                {
                    engine.Execute(functionCode);
                    var result = engine.CallFunction("negate", 22);         //<=== Error here with NiL, function 'negate' not found, OK with Jint
                }
                catch (TimeoutException)
                {
                    Console.WriteLine("Timed out!");
                }`

**Comment by Taritsyn** [comment]
Hello, Dean!

It seems, that this is some kind of error in the NiL.JS, because it occurs only in strict mode. I created a issue in repository of the original project - https://github.com/nilproject/NiL.JS/issues/146

**Comment by deandob** [comment]
Yep, that's it! Thanks for the quick response, and thanks for JSEngineSwitcher, very helpful.

**Comment by Taritsyn** [comment]
By the way, instead of the `TimeoutException` class you need to use the `JsTimeoutException` and timeouts occur only in the JavaScriptEngineSwitcher.Jint module.

**Comment by deandob** [comment]
OK. Thx. I'll close this now.

**Comment by Taritsyn** [comment]
Hello, Dean!

This error is fixed in [version 3.0.0 Beta 9](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.0.0-beta.9).
