### ISSUE TITLE
AddJsEngineSwitcher Missing extension in Asp Net Core 2.1

### ISSUE THREAD

**Issue by SirKillo0o** [Taritsyn/JavaScriptEngineSwitcher#64]
The service collection doesn't have an extension method for the js engine switcher. Thought the current work around for me is JsEngineSwitcher.Current.EngineFactories.AddChakraCore();

**Comment by Taritsyn** [comment]
Hello, Nikolay!

I recommend you to read the [“Registration of JS engines > ASP.NET Core”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Registration-of-JS-engines#aspnet-core) subsection of documentation.
