### ISSUE TITLE
Support for SetVariableValue passing in array and/or js objects?

### ISSUE THREAD

**Issue by bnowlin** [Taritsyn/JavaScriptEngineSwitcher#70]

**Comment by Taritsyn** [comment]
Hello, Brett!

Simple classes (or structures) and delegates can be passed using the `EmbedHostObject` method. Unfortunately, working with collections is not yet supported. But for now, you can use JSON serialization (see an example implementation of [TypeScript compiler](https://github.com/Taritsyn/BundleTransformer/blob/master/src/BundleTransformer.TypeScript/Internal/TypeScriptCompiler.cs)).

Types can be passed using the `EmbedHostType` method.

**Comment by bnowlin** [comment]
Thank you for the examples.

The difference methods confused me as I was expecting the interface to mirror JS.
