### ISSUE TITLE
Method not found: 'JavaScriptEngineSwitcher.Core.JsEngineSwitcher JavaScriptEngineSwitcher.Core.JsEngineSwitcher.get_Current()

### ISSUE THREAD

**Issue by seanrockster** [Taritsyn/JavaScriptEngineSwitcher#76]
Getting this error recently not sure why - kills the site.

mvc .net 4.7

**Comment by Taritsyn** [comment]
Hello, Sean!

What version of the JavaScriptEngineSwitcher.Core did you use before and what version are you using now?

**Comment by seanrockster** [comment]
JavaScriptEngineSwitcher.Core 3.1.0
JavaScriptEngineSwitcher.Msie 3.2.1
MsieJavaScriptEgnine 3.0.5

**Comment by seanrockster** [comment]
Sorry I didn't read your reply properly. I'll look through the repo because it was recently updated...I'll reply shortly.

**Comment by seanrockster** [comment]
JavaScriptEngineSwitcher.Core 1.1.3 => 3.1.0
JavaScriptEngineSwitcher.Msie 1.1.11 => 3.2.1
MsieJavaScriptEgnine 1.4.4 => 3.0.5

**Comment by Taritsyn** [comment]
I recommend you to read the following documents: [“How to upgrade applications to version 2.X”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/How-to-upgrade-applications-to-version-2.X) and [“How to upgrade applications to version 3.X”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/How-to-upgrade-applications-to-version-3.X).

If you are using old versions of the [Bundle Transformer](https://github.com/Taritsyn/BundleTransformer) and [ReactJS.NET](https://github.com/reactjs/React.NET), then you need to update them too.

**Comment by seanrockster** [comment]
Ok thanks.
