### ISSUE TITLE
Debugging not enabled for V8

### ISSUE THREAD

**Issue by justengland** [Taritsyn/JavaScriptEngineSwitcher#8]
I noticed that debugging is not enabled for the V8 clearscript interface. Its a pretty easy change to enable the debugging interface. I have manually made the change and it works fine.

http://pandeysk.wordpress.com/2014/05/25/debugging-with-clearscript/

**Comment by Taritsyn** [comment]
In the [JavaScriptEngineSwitcher.V8 version 1.2.3](http://nuget.org/packages/JavaScriptEngineSwitcher.V8/1.2.3) was implemented this feature. You can specify the configuration settings of V8 JavaScript engine in the configuration files (`Web.config` or `App.config`) or by passing it to the constructor of class `V8JsEngine`. I would also recommend to install the latest version of the [JavaScriptEngineSwitcher.ConfigurationIntelliSense](http://nuget.org/packages/JavaScriptEngineSwitcher.ConfigurationIntelliSense) package.
