### ISSUE TITLE
Javascript.Net

### ISSUE THREAD

**Issue by miloszkukla** [Taritsyn/JavaScriptEngineSwitcher#80]
Just for a future reference - there is also https://github.com/JavascriptNet/Javascript.Net - I don't know what is the status of it neither does it make sense to add yet another V8 bindings to this project. Feel free to close this issue.

**Comment by Taritsyn** [comment]
Abandoned this library in favor of the ClearScript in [version 0.9.5](https://www.nuget.org/packages/JavaScriptEngineSwitcher.V8/0.9.5).

Now I am working in [separate branch](https://github.com/Taritsyn/JavaScriptEngineSwitcher/tree/node-js-engine) on a new module based on the [Jering.Javascript.NodeJS](https://github.com/JeringTech/Javascript.NodeJS) library.
