### ISSUE TITLE
Invalid output folder for ClearScript dependencies in _PublishedWebsites when build project with MsBuild

### ISSUE THREAD

**Issue by Qmannn** [Taritsyn/JavaScriptEngineSwitcher#83]
Project: ASP.NET Web Application (Net.Framework 4.7.1)

When I build my project with VS2019 in output directory I can see folder x64 with files:
![image](https://user-images.githubusercontent.com/10262301/76704944-75ed7500-66ed-11ea-90b5-5d830fc2ee5f.png)

But if I build a project with MsBuild by specifying a third-party output directory , the directory structure in the output Bin folder is incorrect.

Output folder structure:
test_out_folder
![image](https://user-images.githubusercontent.com/10262301/76705199-43447c00-66ef-11ea-960f-b57dcf69aef8.png)
This folder contains x64 folder - it's look good, but folder `_PublishedWebsites/JSSwitchTest/bin` look differently.

![image](https://user-images.githubusercontent.com/10262301/76705246-9fa79b80-66ef-11ea-8008-d8b15ec976a9.png)

It doesn't contains folder x64, but all files from this folder copied into root bin folder path (on screen above).

The problem is that I use the _publishedwebsites folder as the source of the built application , but with this folder structure, I get a Filenotfoundexception when the application starts because the x64 folder does not exist in my application 's Bin directory

**Step to reproduse**

**1** Create ASP.NET Web Application in VS2019

**2** Install Nuget package JavaScriptEngineSwitcher.V8.Native.win-x64

**3** Build project into custom output folder with MsBuild
In my case the msbuild call looked like this:
`MSBuild.exe "D:\github\JSSwitchTest\JSSwitchTest.sln" /p:OutputPath=D:\dev\test_out_folder`

I'm sorry for my English...

**Comment by Taritsyn** [comment]
Everything works correctly for me:

<img src="https://i.imgur.com/iRt7s0e.png" />

**Comment by Qmannn** [comment]
I used MsBuild version 14. On version 16, the build was successful. Thank you very much!
