### ISSUE TITLE
Add configuration for each engine

### ISSUE THREAD

**Issue by huan086** [Taritsyn/JavaScriptEngineSwitcher#9]
The Clearscript V8 engine allows for V8ScriptEngineFlags that turns on debugging and DisableGlobalMembers. It's constructor also accepts V8RuntimeConstraints.

It would be good if consumers can define a class with the configuration for each engine, so as to pass V8RuntimeConstraints and V8ScriptEngineFlags for the V8 engine, or some other parameters for other engines.

**Comment by Daniel15** [comment]
+1 This is a good idea. Perhaps configuration could be allowed via the
Web.config or app.config too.

**Comment by Taritsyn** [comment]
In the [JavaScriptEngineSwitcher.V8 version 1.2.3](http://nuget.org/packages/JavaScriptEngineSwitcher.V8/1.2.3) was implemented this feature. You can specify the configuration settings of V8 JavaScript engine in the configuration files (`Web.config` or `App.config`) or by passing it to the constructor of class `V8JsEngine`. I would also recommend to install the latest version of the [JavaScriptEngineSwitcher.ConfigurationIntelliSense](http://nuget.org/packages/JavaScriptEngineSwitcher.ConfigurationIntelliSense) package.

Similar functionality will be gradually added to other engines.
