### ISSUE TITLE
It's possible to reset IJSEngine state?

### ISSUE THREAD

**Issue by coader** [Taritsyn/JavaScriptEngineSwitcher#90]
I have a script snippet, should be executed many times
so i precompile it at first, but every time execute, the engine still keep last  state, 
so get error: redeclared

code just like this:
`'use strict'; 
const x=1+2+3+4; 
let y=2; 
function run( ){
return  x*x;
}`

**Comment by Taritsyn** [comment]
It's impossible. Rewrite your code as a function with parameters and execute it once. Then call the function with different parameters.

**Comment by Taritsyn** [comment]
Although you can try manually removing a `x`, `y` and `run` global variables.

**Comment by coader** [comment]
got it, tks

**Comment by coader** [comment]
sorry for this issue, still another question, as it execute many times, so it's threadsafe for compile and execute?

**Comment by Taritsyn** [comment]
Yes, these operations are threadsafe. There is even a [test to check this](https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/253b476620b07220fa9c62d1104d24067bfc4d7e/test/JavaScriptEngineSwitcher.Tests/PrecompilationTestsBase.cs#L14-L84).
