### ISSUE TITLE
Loading of sourcemaps from webpack compiled scripts

### ISSUE THREAD

**Issue by magnusottosson** [Taritsyn/JavaScriptEngineSwitcher#93]
Hi,

I'm using the ReactJS.NET (https://github.com/reactjs/React.NET) package to server side render react components. I pre-compile the scripts using webpack. ReactJS.NET is using this package for JS engines and I'm using the V8 Engine from Microsoft.ClearScript

Is it possible to load pre-compiled sourcemaps (.map) files?

I see that ClearScript has a DocumentInfo where you can add the Uri of the source map but that is not exposed correct?

**Comment by Taritsyn** [comment]
Hello, Magnus!

> Is it possible to load pre-compiled sourcemaps (.map) files?

No.

> I see that ClearScript has a DocumentInfo where you can add the Uri of the source map but that is not exposed correct?

Yes, this functionality is not supported. JavaScript Engine Switcher  is focused only on supporting the basic features of JS engines. If similar functionality appears in other JS engines, then I will start considering variants for adding it to API.

**Comment by magnusottosson** [comment]
Thanks for the reply. I ended up using https://github.com/sleeuwen/sourcemaps to enrich the stacktrace outside of the JS-engine which works just as good!
