### ISSUE TITLE
How to pass c# objects to JavaScript functions?

### ISSUE THREAD

**Issue by CeSun** [Taritsyn/JavaScriptEngineSwitcher#96]
![image](https://user-images.githubusercontent.com/54771283/133241141-5cb59fc0-c6c3-4eac-ad8d-a2fa16358c90.png)

**Comment by Taritsyn** [comment]
Hello!

This cannot be done. 

You can use the `Execute` or `Evaluate` method of JS engine with JSON serialization:

```csharp
var myObj = new Obj();
string serializedObj = JsonConvert.SerializeObject(myObj);
jsEngine.Execute("fun(" + serializedObj + ");");
```

If you need an active object, then you can embed it:

```csharp
var myObj = new Obj();
jsEngine.EmbedHostObject("myObj", myObj);
jsEngine.Execute("fun(myObj);");
```

**Comment by CeSun** [comment]
Thank you!
